### ISSUE TITLE
Demeter Design

### ISSUE THREAD

**Issue by arvifox** [sora-xor/sora-mobile#8]
notes from the grooming on Demeter

- [ ] Demeter view OK; Need Demeter view from LP
- [ ] Loading states
- [ ] Error states
- [ ] Cases: Farming active or inactive
- [ ] Agree on unified naming among platforms (is it correct to say *stake* more liquidity ?)
- [ ] Screen flows / prototype

**Comment by Trezeguet1** [comment]
Acceptance criteria:

1. Buttons to add a pool
2. Screen with active and inactive farms in pool details
3. Claim Reward
4. Add/Remove Liquidity from Farm TX Details
5. Claim Reward TX Details
6. Search feature
